# Generated by Django 5.0.4 on 2026-04-27 17:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shifts", "0001_initial"),
        ("stations", "0001_initial"),
        ("tanks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pump",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Pump number/label on forecourt"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Pump 1, Island A", max_length=100),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="e.g. Gilbarco Encore 700", max_length=100
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_calibration", models.DateField(blank=True, null=True)),
                ("next_calibration", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Under Maintenance"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pumps",
                        to="stations.station",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary tank supplying this pump",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pumps",
                        to="tanks.tank",
                    ),
                ),
            ],
            options={
                "db_table": "pumps",
                "ordering": ["station", "number"],
            },
        ),
        migrations.CreateModel(
            name="Nozzle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Nozzle number on pump (1, 2, 3...)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("faulty", "Faulty"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "current_reading",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stations.fueltype",
                    ),
                ),
                (
                    "pump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="pumps.pump",
                    ),
                ),
            ],
            options={
                "db_table": "nozzles",
                "ordering": ["pump", "number"],
            },
        ),
        migrations.CreateModel(
            name="ShiftNozzleReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "opening_reading",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "closing_reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "litres_sold",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "test_litres",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=8
                    ),
                ),
                ("opening_recorded_at", models.DateTimeField(auto_now_add=True)),
                ("closing_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "nozzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_readings",
                        to="pumps.nozzle",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzle_readings",
                        to="shifts.shift",
                    ),
                ),
            ],
            options={
                "db_table": "shift_nozzle_readings",
            },
        ),
        migrations.AddIndex(
            model_name="pump",
            index=models.Index(
                fields=["station", "status"], name="pumps_station_7a7b2e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pump",
            unique_together={("station", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="nozzle",
            unique_together={("pump", "number")},
        ),
        migrations.AddIndex(
            model_name="shiftnozzlereading",
            index=models.Index(
                fields=["shift", "nozzle"], name="shift_nozzl_shift_i_1b8731_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shiftnozzlereading",
            unique_together={("shift", "nozzle")},
        ),
    ]
