# Generated by Django 5.0.4 on 2026-04-27 17:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shifts", "0001_initial"),
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "name",
                    models.CharField(help_text="e.g. Tank 1 (Petrol)", max_length=100),
                ),
                (
                    "capacity_litres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total tank capacity in litres",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "safe_fill_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum safe fill level (usually 95% of capacity)",
                        max_digits=12,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock level that triggers reorder alert",
                        max_digits=12,
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current estimated stock in litres",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Under Maintenance"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_inspection", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stations.fueltype",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "tanks",
                "ordering": ["station", "number"],
                "unique_together": {("station", "number")},
            },
        ),
        migrations.CreateModel(
            name="FuelDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivery_note_number", models.CharField(max_length=50)),
                ("supplier", models.CharField(max_length=200)),
                ("vehicle_reg", models.CharField(blank=True, max_length=20)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_phone", models.CharField(blank=True, max_length=20)),
                (
                    "ordered_litres",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "delivered_litres",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "variance_litres",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "dip_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Litres in tank before delivery",
                        max_digits=12,
                    ),
                ),
                (
                    "dip_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_per_litre",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("verified", "Verified"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="stations.station",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="tanks.tank",
                    ),
                ),
            ],
            options={
                "db_table": "fuel_deliveries",
                "ordering": ["-delivered_at"],
                "indexes": [
                    models.Index(
                        fields=["station", "delivered_at"],
                        name="fuel_delive_station_cd3b86_idx",
                    ),
                    models.Index(
                        fields=["tank", "delivered_at"],
                        name="fuel_delive_tank_id_7bc193_idx",
                    ),
                    models.Index(
                        fields=["status"], name="fuel_delive_status_22ba4e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DipReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening"),
                            ("closing", "Closing"),
                            ("spot", "Spot Check"),
                        ],
                        default="closing",
                        max_length=20,
                    ),
                ),
                (
                    "dip_mm",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Dip stick reading in mm",
                        max_digits=8,
                    ),
                ),
                (
                    "litres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Converted litres from dip chart",
                        max_digits=12,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "book_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dip_readings",
                        to="shifts.shift",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dip_readings",
                        to="tanks.tank",
                    ),
                ),
            ],
            options={
                "db_table": "dip_readings",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["tank", "recorded_at"],
                        name="dip_reading_tank_id_a4b508_idx",
                    ),
                    models.Index(
                        fields=["shift"], name="dip_reading_shift_i_fdbc6f_idx"
                    ),
                ],
            },
        ),
    ]
