# Generated by Django 5.0.4 on 2026-04-27 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#gray",
                        help_text="Hex color for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="L", help_text="Unit of measure", max_length=10
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Density in kg/L for mass calculations",
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "fuel_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Station short code e.g. NRB-001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("address", models.TextField()),
                ("county", models.CharField(default="Nairobi", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kra_pin",
                    models.CharField(
                        blank=True, help_text="KRA PIN for tax purposes", max_length=20
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("operates_24hrs", models.BooleanField(default=True)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("mpesa_shortcode", models.CharField(blank=True, max_length=20)),
                ("mpesa_till", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StationFuelPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_per_litre",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.fueltype",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_prices",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "db_table": "station_fuel_prices",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["station", "fuel_type", "is_current"],
                        name="station_fue_station_0d4482_idx",
                    )
                ],
            },
        ),
    ]
